In [6]:
import numpy as np

In [5]:
def tsqr(W):
    
    # Divide matrix into 4 row blocks
    m, n = W.shape
    num_blocks = 4
    block_size = m // num_blocks
    W_blocks = [W[i * block_size: (i + 1) * block_size, :] for i in range(num_blocks)]
    
    # Perform local QR on each block
    Q_blocks = []
    R_blocks = []
    for W_block in W_blocks:
        Q, R = np.linalg.qr(W_block)
        Q_blocks.append(Q)
        R_blocks.append(R)
    
    # Stack the R factors and compute a second-level QR
    R_stacked = np.vstack(R_blocks)
    Q_final, R_final = np.linalg.qr(R_stacked)
    
    # Compute final Q by multiplying block Qs with Q_final
    Q_combined = np.vstack([Q_blocks[i] @ Q_final[i*n:(i+1)*n, :] for i in range(num_blocks)])
    
    return Q_combined, R_final

# Test usage
m, n = 16, 4  
W = np.random.rand(m, n)

Q, R = tsqr(W)

# Verify that Q is orthogonal and R is upper triangular
print("Q.T @ Q :\n", np.round(Q.T @ Q, 5))
print("R \n", np.round(R, 5))


Q.T @ Q :
 [[ 1.  0. -0.  0.]
 [ 0.  1. -0.  0.]
 [-0. -0.  1.  0.]
 [ 0.  0.  0.  1.]]
R 
 [[2.02542 1.8603  1.79842 1.97237]
 [0.      1.75832 0.23106 0.634  ]
 [0.      0.      1.63625 0.57125]
 [0.      0.      0.      1.30658]]
